services:
  - type: web
    name: cil-tracker
    env: docker
    plan: free
    buildCommand: docker build -t cil-tracker .
    startCommand: docker run -p $PORT:8000 cil-tracker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cil_tracker_db
          property: connectionString
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000

databases:
  - name: cil_tracker_db
    databaseName: cil_tracker
    user: cil_tracker
    plan: free 